name = "FromFile"
uuid = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MatchCore = "5dd3f0b1-72a9-48ad-ae6e-79f673da005f"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
