name = "FromFile"
uuid = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
authors = ["Roger Luo <rogerluo.rl18@gmail.com> and Patrick Kidger <contact@kidger.site>"]
version = "0.1.4"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Requires = "1.3"
julia = "1.6"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Revise", "Test"]
